### ISSUE TITLE
Error while installing please help me

### ISSUE THREAD

**Issue by venkat2305** [gnuhead-chieb/revanced-automatic-builder#14]
![Screenshot_2023-01-10-23-43-21-142_com.termux.jpg](https://user-images.githubusercontent.com/55329452/211630515-34d8f631-670c-45d3-8d49-65f374ef584c.jpg)

What should I do.
I copied the code and pasted it in termux.

**Comment by gnuhead-chieb** [comment]
Yeah this is known issue.
Workaround: Run `apt install --fix-broken` and run installer snippet again.

**Comment by venkat2305** [comment]
also, getting this error on pc 
![image](https://user-images.githubusercontent.com/55329452/211717888-9de53ce5-ae26-4a4d-affa-113b63b8ea35.png)
I have ubuntu and wsl installed

**Comment by gnuhead-chieb** [comment]
This tool not officially tested on WSL and I don't use Windows.(but probably work)
However, the error seems to indicate that your procedure is wrong, not a problem on my side.

Follow this instruction carefully.
https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-10#1-overview

**Comment by gnuhead-chieb** [comment]
Anyway fixed installer snippet for Termux in https://github.com/gnuhead-chieb/revanced-automatic-builder/commit/e1927ac29b75133e772e4588a0c10f805a14a2b0

**Comment by gnuhead-chieb** [comment]
Did you worked on WSL?

**Comment by venkat2305** [comment]
I will try again

**Comment by venkat2305** [comment]
![image](https://user-images.githubusercontent.com/55329452/212034159-5107e2fb-73a8-4e41-bf9b-eb70274a4446.png)

![image](https://user-images.githubusercontent.com/55329452/212034615-9af5638a-c49d-4a45-8983-1ff85e87c090.png)

**Comment by gnuhead-chieb** [comment]
Of course, you must install dependencies yourself if you use this script on PC.
Installer script doesn't install automatically for PC.(due to it is complex to support many distros)

For ubuntu install them by running `sudo apt install wget openjdk-17 openssl jq adb`
