### ISSUE TITLE
Add option to install wget by default! 

### ISSUE THREAD

**Issue by Lucky-069** [gnuhead-chieb/revanced-automatic-builder#8]
I have tried to setup the script from scratch and whenever wget is absent the script returns error, even tho it uses curl, perhaps curl breaks downloads at times as it downloads files faster. Only after I install wget the script starts to work normally!

**Comment by gnuhead-chieb** [comment]
wget is using for downloading binaries or apk from github/apkcombo.
curl is using for retrive API responce(text data)

in Termux,curl is install by default if you using latest version from F-Droid,wget will be installed when you ran installer script
